version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  api-gateway:
    image: public.ecr.aws/h7r7v5j6/eventify/api-gateway:latest
    container_name: api-gateway
    command: node dist/main
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
  user-service:
    image: public.ecr.aws/h7r7v5j6/eventify/user-service:latest
    container_name: user-service
    command: node dist/main
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NATS_URL=nats://nats:4222
      - MONGO_URI=mongodb://user-mongo:27017/users
    depends_on:
      - nats
      - user-mongo
  event-service:
    build: ../eventify-event-service
    container_name: event-service
    command: node dist/main
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NATS_URL=nats://nats:4222
      - MONGO_URI=mongodb://event-mongo:27018/events
    depends_on:
      - nats
      - event-mongo
  event-mongo:
    image: mongo:latest
    container_name: event-mongo
    ports:
      - "27018:27017"
    volumes:
      - event-data:/data/db
  user-mongo:
    image: mongo:latest
    container_name: user-mongo
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.12
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.12
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.12
    container_name: filebeat
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3003:3000"
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  user-data:
  event-data:
  grafana-data:


