global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "event-service"
    static_configs:
      - targets: ["event-service:3002"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:3001"]
